[project]
name = "oscar-nextgen"
version = "0.1.0"
description = "WMDR10 Metadata Handling for OASIS"
authors = [{name = "Jörg Klausen (joerg.klausen@meteoswiss.ch)"}]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["acdd", "wmdr"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
